FROM docker.io/library/almalinux:${release}

RUN sed -i /etc/yum.repos.d/almalinux*.repo \
      -e 's/^# baseurl=/baseurl=/' \
      -e 's/^mirrorlist=/# mirrorlist=/' \
      -e 's/\$releasever/${release}/' \
    && dnf clean all

RUN mkdir /boot # missing in the container
RUN dnf update -y \
    && dnf install -y --allowerasing \
      coreutils \
      cpio \
      e2fsprogs \
      ethtool \
      findutils \
      initscripts \
      ipmitool \
      iproute \
      kernel-core \
      kernel-modules \
      net-tools \
      NetworkManager \
      nfs-utils \
      openssh-clients \
      openssh-server \
      pciutils \
      psmisc \
      rsync \
      rsyslog \
      strace \
      wget \
      which \
    && dnf remove -y selinux-policy \
    && dnf clean all

RUN systemctl unmask \
      console-getty.service \
      dev-hugepages.mount \
      getty.target \
      sys-fs-fuse-connections.mount \
      systemd-logind.service \
      systemd-remount-fs.service

RUN chmod u+w / # https://github.com/openhpc/ohpc/issues/2061
RUN userdel systemd-coredump # remove unused dynamic system user

COPY excludes /etc/warewulf/
COPY image_exit.sh /etc/warewulf/
RUN ln -sf image_exit.sh /etc/warewulf/container_exit.sh && /etc/warewulf/image_exit.sh

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
