FROM ghcr.io/warewulf/warewulf-rockylinux:8.10

ARG MOFED_TGZ

RUN dnf -y install \
        kernel-{core,devel,headers,modules-extra} \
        autoconf \
        patch \
        libtool \
        rpm-build \
        kernel-rpm-macros \
        gdb-headless \
        automake \
        gcc-gfortran \
        tcl \
        tk \
        libnl3 \
        lsof \
        numactl-libs \
        python36 \
    && dnf -y remove $(dnf repoquery --installonly --latest-limit=-1 -q) \
    && dnf clean all

RUN (cd /tmp && tar -xf /mnt/$MOFED_TGZ) \
    && (cd /tmp/MLNX_OFED_LINUX* && ./mlnxofedinstall --distro rhel8.10 --skip-repo --kernel $(rpm -q kernel-core --qf '%{version}-%{release}.%{arch}\n' | tail -n 1) --add-kernel-support --hpc --without-fw-update) \
    && rm -rf /tmp/MLNX_OFED_LINUX* /etc/machine-id
