FROM ghcr.io/warewulf/warewulf-rockylinux:9.4

ARG MOFED_TGZ

RUN dnf -y install \
        gcc \
        patch \
        libtool \
        lsof \
        kernel-rpm-macros \
        make \
        rpm-build \
        gdb-headless \
        python3-devel \
        elfutils-libelf-devel \
        gcc-gfortran \
        libnl3 \
        tk \
        kernel-{core,devel,headers,modules-extra} \
        perl-sigtrap \
        numactl-libs \
        tcsh \
    && dnf -y remove $(dnf repoquery --installonly --latest-limit=-1 -q) \
    && dnf clean all

RUN (cd /tmp && tar -xf /mnt/$MOFED_TGZ) \
    && (cd /tmp/MLNX_OFED_LINUX* && ./mlnxofedinstall --distro rhel9.4 --skip-repo --kernel $(rpm -q kernel-core --qf '%{version}-%{release}.%{arch}\n' | tail -n 1) --add-kernel-support --hpc --without-fw-update) \
    && rm -rf /tmp/MLNX_OFED_LINUX* /etc/machine-id
