FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=teletype
RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        apt-utils \
        kmod \
        init \
        udev \
        systemd-sysv \
        dbus \
        openssh-client \
        openssh-server \
        nfs-common \
        linux-image-generic \
        ifupdown \
        netbase \
        netplan.io \
        libnetplan1 \
        python3-netplan \
        networkd-dispatcher \
        ethtool\
        ifmetric \
        pciutils \
        pci.ids \
        mawk \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY excludes /etc/warewulf/
COPY image_exit.sh /etc/warewulf/
RUN ln -sf image_exit.sh /etc/warewulf/container_exit.sh && /etc/warewulf/image_exit.sh

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
