FROM docker.io/library/rockylinux:9.3

RUN rm -f /etc/yum.repos.d/*.repo \
    && dnf clean all

COPY yum.repos.d-9.3/*.repo /etc/yum.repos.d

RUN dnf update -y \
    && dnf install -y --allowerasing \
      coreutils \
      cpio \
      dhclient \
      e2fsprogs \
      ethtool \
      findutils \
      initscripts \
      ipmitool \
      iproute \
      kernel-core \
      kernel-modules \
      ncurses \
      net-tools \
      NetworkManager \
      nfs-utils \
      openssh-clients \
      openssh-server \
      pciutils \
      policycoreutils-python-utils \
      psmisc \
      rsync \
      rsyslog \
      strace \
      selinux-policy-targeted \
      wget \
      which \
      words \
      rdma-core \
    && dnf clean all

RUN touch /etc/sysconfig/disable-deprecation-warnings

# For SELinux enabled nodes:
#   The wwclient service fails to start on boot if appropriate SELinux file
#   context label is not set for /warewulf/wwclient.
#   Permanently assign bin_t fcontent label for wwclient binary that is
#   deployed by wwinit overlay because warewulf runs `restorecon -R /` on node
#   boot, clobbering any existing labels set in the overlay itself.
#
RUN semanage fcontext -N -a -t bin_t /warewulf/wwclient

COPY excludes /etc/warewulf/
COPY container_exit.sh /etc/warewulf/

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
