FROM rockylinux:9

RUN dnf update -y \
    && dnf install -y --allowerasing \
      coreutils \
      cpio \
      dhclient \
      e2fsprogs \
      ethtool \
      findutils \
      initscripts \
      ipmitool \
      iproute \
      kernel-core \
      kernel-modules \
      ncurses \
      net-tools \
      NetworkManager \
      nfs-utils \
      openssh-clients \
      openssh-server \
      pciutils \
      policycoreutils-python-utils \
      psmisc \
      rsync \
      rsyslog \
      strace \
      selinux-policy-targeted \
      wget \
      which \
      words \
      rdma-core \
    && dnf clean all

RUN touch /etc/sysconfig/disable-deprecation-warnings

RUN semanage fcontext -N -a -t bin_t /warewulf/wwclient

COPY excludes /etc/warewulf/
COPY container_exit.sh /etc/warewulf/

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
