FROM opensuse/tumbleweed:latest
RUN zypper update -y \
    && zypper install -yt pattern \
        base \
    && zypper install -y \
        bash \
        coreutils \
        cpio \
        cronie \
        e2fsprogs \
        ethtool \
        filesystem \
        findutils \
        gawk \
        grep \
        gzip \
        ipmitool \
        iproute2 \
        iputils \
        kernel-default \
        less \
        NetworkManager \
        nfs-client \
        openssh-clients \
        openssh-server \
        pam \
        pciutils \
        psmisc \
        rsync \
        rsyslog \
        sed \
        strace \
        sudo \
        systemd \
        tar \
        tcpdump \
        timezone \
        udev \
        util-linux \
        wget \
        which \
        zypper \
    && zypper clean \
    && systemd-hwdb update \
    && systemctl enable sshd \
    && systemctl enable NetworkManager

COPY excludes /etc/warewulf/
COPY image_exit.sh /etc/warewulf/
RUN ln -sf image_exit.sh /etc/warewulf/container_exit.sh && /etc/warewulf/image_exit.sh

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
