FROM debian:12

# ----- install vital packages -----
ENV DEBIAN_FRONTEND=teletype
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
	kmod \
	systemd-sysv \
	dbus \
	openssh-client \
	openssh-server \
	pciutils \
	nfs-common \
	ethtool\
	ifupdown \
	linux-image-$(dpkg --print-architecture) \
	ifmetric \
	netbase && \
	rm -rf /var/lib/apt/lists/*

COPY excludes /etc/warewulf/
COPY image_exit.sh /etc/warewulf/
RUN ln -sf image_exit.sh /etc/warewulf/container_exit.sh && /etc/warewulf/image_exit.sh

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
