FROM ghcr.io/warewulf/warewulf-rockylinux:9.4

RUN dnf -y install https://repo.radeon.com/amdgpu-install/6.2.2/el/9.4/amdgpu-install-6.2.60202-1.el9.noarch.rpm \
    && dnf clean all \
    && amdgpu-install -y --usecase=dkms \
    && ls /lib/modules | xargs -n1 /usr/lib/dkms/dkms_autoinstaller start \
    && dkms status
