FROM docker.io/opensuse/leap:latest
RUN zypper update -y \
    && zypper install -yt pattern \
        base \
    && zypper install -y \
        bash \
        coreutils \
        cpio \
        cronie \
        e2fsprogs \
        ethtool \
        filesystem \
        findutils \
        gawk \
        grep \
        gzip \
        ifplugd \
        ipmitool \
        iproute2 \
        iputils \
        kernel-default \
        less \
        net-tools \
        nfs-client \
        openssh-clients \
        openssh-server \
        pam \
        pciutils \
        psmisc \
        rsync \
        rsyslog \
        sed \
        strace \
        sudo \
        tar \
        tcpdump \
        timezone \
        util-linux \
        vim \
        wget \
        which \
        wicked \
        words \
        zypper \
    && zypper clean \
    && systemctl enable sshd 

COPY excludes /etc/warewulf/
COPY container_exit.sh /etc/warewulf/
RUN /etc/warewulf/container_exit.sh

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
