FROM docker.io/library/almalinux:${release}

RUN sed -i /etc/yum.repos.d/almalinux*.repo \
      -e 's/^# baseurl=/baseurl=/' \
      -e 's/^mirrorlist=/# mirrorlist=/' \
      -e 's/\$releasever/${release}/' \
    && dnf clean all

RUN dnf update -y \
    && dnf install -y --allowerasing \
      coreutils \
      cpio \
      e2fsprogs \
      ethtool \
      findutils \
      initscripts \
      ipmitool \
      iproute \
      kernel-core \
      kernel-modules \
      net-tools \
      NetworkManager \
      nfs-utils \
      openssh-clients \
      openssh-server \
      pciutils \
      psmisc \
      rsync \
      rsyslog \
      strace \
      wget \
      which \
      words \
    && dnf remove -y selinux-policy \
    && dnf clean all

RUN chmod u+w / # https://github.com/openhpc/ohpc/issues/2061
# remove unused dynamic system user
RUN userdel systemd-oom && \
    userdel systemd-coredump

COPY excludes /etc/warewulf/
COPY container_exit.sh /etc/warewulf/
RUN /etc/warewulf/container_exit.sh

CMD [ "/bin/echo", "-e", \
      "This image is intended to be used with the Warewulf cluster management and", \
      "\nprovisioning system.", \
      "\n", \
      "\nFor more information about Warewulf, visit https://warewulf.org" ]
