name: Build and publish OCI images

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: rockylinux
            version: "8"
            context: rockylinux-8
            file: rockylinux-8/Containerfile
          - os: rockylinux
            version: "8.9"
            context: rockylinux-8
            file: rockylinux-8/Containerfile-8.9
          - os: rockylinux
            version: "8.10"
            context: rockylinux-8
            file: rockylinux-8/Containerfile-8.10
          - os: rockylinux
            version: "9"
            context: rockylinux-9
            file: rockylinux-9/Containerfile
          - os: rockylinux
            version: "9.5"
            context: rockylinux-9
            file: rockylinux-9/Containerfile-9.5
          - os: rockylinux
            version: "9.6"
            context: rockylinux-9
            file: rockylinux-9/Containerfile-9.6
          - os: rockylinux
            version: "10"
            context: rockylinux-10
            file: rockylinux-10/Containerfile
          - os: rockylinux
            version: "10.0"
            context: rockylinux-10
            file: rockylinux-10/Containerfile-10.0
          - os: almalinux
            version: "8"
            context: almalinux-8
            file: almalinux-8/Containerfile
          - os: almalinux
            version: "8.9"
            context: almalinux-8
            file: almalinux-8/Containerfile-8.9
          - os: almalinux
            version: "8.10"
            context: almalinux-8
            file: almalinux-8/Containerfile-8.10
          - os: almalinux
            version: "9"
            context: almalinux-9
            file: almalinux-9/Containerfile
          - os: almalinux
            version: "9.5"
            context: almalinux-9
            file: almalinux-9/Containerfile-9.5
          - os: almalinux
            version: "9.6"
            context: almalinux-9
            file: almalinux-9/Containerfile-9.6
          - os: almalinux
            version: "10"
            context: almalinux-10
            file: almalinux-10/Containerfile
          - os: almalinux
            version: "10.0"
            context: almalinux-10
            file: almalinux-10/Containerfile-10.0
          - os: leap
            version: "15"
            context: leap
            file: leap/Containerfile.15
          - os: leap
            version: latest
            context: leap
            file: leap/Containerfile
          - os: tumbleweed
            version: latest
            context: tumbleweed
            file: tumbleweed/Containerfile
          - os: debian
            version: "12.0"
            context: debian
            file: debian/Containerfile-12.0

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make Containerfiles
        run: |
          make -C rockylinux-8
          make -C rockylinux-9
          make -C rockylinux-10
          make -C almalinux-8
          make -C almalinux-9
          make -C almalinux-10

      # Install the cosign tool
      # https://github.com/sigstore/cosign-installer
      - name: Install Cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.5.0

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7

      # Login against a Docker registry
      # https://github.com/docker/login-action
      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/warewulf-${{ matrix.os }}
          tags: |
            type=schedule
            type=raw,${{ matrix.version }}

      # Build and push Docker image with Buildx
      # https://github.com/docker/build-push-action
      - name: Build and push image
        id: build-and-push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.file }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
      - name: Sign the images with GitHub OIDC Token
        if: github.event_name != 'pull_request'
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: cosign sign --yes "${TAGS}@${DIGEST}"
